import React from 'react';
import { motion } from 'framer-motion';
import { Clock, CheckCircle, AlertCircle, ArrowRight } from 'lucide-react';
export function ForProfessionals() {
  return (
    <section id="professionals" className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-12">
          <span className="text-uts-teal font-bold tracking-widest text-sm uppercase mb-2 block">
            Audience
          </span>
          <h2 className="text-3xl md:text-4xl font-bold text-uts-navy mb-6">
            For Professionals
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl">
            Adopt the tools of the future with help from the next generation.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          {/* Main Content */}
          <div className="lg:col-span-7 space-y-12">
            {/* What You Get */}
            <div>
              <h3 className="text-2xl font-bold text-gray-900 mb-6">
                What You Get
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
                  <h4 className="font-bold text-uts-navy mb-2">
                    Half-Day Setup
                  </h4>
                  <p className="text-gray-600 text-sm">
                    A dedicated session to install, configure, and learn Claude
                    Cowork on your own device.
                  </p>
                </div>
                <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
                  <h4 className="font-bold text-uts-navy mb-2">
                    3 Custom Workflows
                  </h4>
                  <p className="text-gray-600 text-sm">
                    Tailored AI processes for your specific needs (e.g., email
                    triage, research, scheduling).
                  </p>
                </div>
                <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
                  <h4 className="font-bold text-uts-navy mb-2">
                    Ongoing Support
                  </h4>
                  <p className="text-gray-600 text-sm">
                    Students remain on-call for questions and tweaks ($50/mo
                    maintenance).
                  </p>
                </div>
                <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
                  <h4 className="font-bold text-uts-navy mb-2">No Data Risk</h4>
                  <p className="text-gray-600 text-sm">
                    Everything runs on your computer. Students never take your
                    data home.
                  </p>
                </div>
              </div>
            </div>

            {/* The Process */}
            <div>
              <h3 className="text-2xl font-bold text-gray-900 mb-6">
                What a Session Looks Like
              </h3>
              <div className="space-y-6">
                <div className="flex">
                  <div className="flex-shrink-0 mr-4">
                    <div className="w-8 h-8 rounded-full bg-uts-navy text-white flex items-center justify-center font-bold">
                      1
                    </div>
                  </div>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900">
                      AI-Powered Discovery (60 min)
                    </h4>
                    <p className="text-gray-600">
                      The student runs a structured intake prompt where Claude
                      asks you questions to identify your needs.
                    </p>
                  </div>
                </div>
                <div className="flex">
                  <div className="flex-shrink-0 mr-4">
                    <div className="w-8 h-8 rounded-full bg-uts-navy text-white flex items-center justify-center font-bold">
                      2
                    </div>
                  </div>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900">
                      Review & Refine (30 min)
                    </h4>
                    <p className="text-gray-600">
                      You review the project brief generated by Claude and
                      confirm the 3 workflows to build.
                    </p>
                  </div>
                </div>
                <div className="flex">
                  <div className="flex-shrink-0 mr-4">
                    <div className="w-8 h-8 rounded-full bg-uts-navy text-white flex items-center justify-center font-bold">
                      3
                    </div>
                  </div>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900">
                      Setup & Configuration (90 min)
                    </h4>
                    <p className="text-gray-600">
                      The student installs the software, configures the
                      environment, and builds the workflows with you.
                    </p>
                  </div>
                </div>
                <div className="flex">
                  <div className="flex-shrink-0 mr-4">
                    <div className="w-8 h-8 rounded-full bg-uts-navy text-white flex items-center justify-center font-bold">
                      4
                    </div>
                  </div>
                  <div>
                    <h4 className="text-lg font-bold text-gray-900">
                      Handoff (30 min)
                    </h4>
                    <p className="text-gray-600">
                      Documentation, instructions for next steps, and
                      maintenance agreement.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Intake Prompt Quote */}
            <div className="bg-uts-offwhite p-6 rounded-lg border-l-4 border-uts-teal italic text-gray-700">
              <p className="mb-2 font-semibold not-italic text-uts-navy">
                The "Secret Sauce" Intake Prompt:
              </p>
              "We are going to set up the first 3 Claude Cowork processes for
              you... Ask me questions 1 by 1 until we get clear. Then output a
              project brief..."
              <p className="mt-2 text-sm text-gray-500 not-italic">
                — Students use this prompt to let the AI do the heavy lifting of
                discovery.
              </p>
            </div>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-5 space-y-8">
            <div className="bg-uts-navy text-white p-8 rounded-xl shadow-lg">
              <h3 className="text-2xl font-bold mb-6">Investment</h3>
              <div className="space-y-6">
                <div className="flex justify-between items-center border-b border-white/20 pb-4">
                  <span>Setup Session</span>
                  <span className="text-2xl font-bold text-uts-teal">$200</span>
                </div>
                <div className="flex justify-between items-center border-b border-white/20 pb-4">
                  <span>Monthly Support</span>
                  <span className="text-2xl font-bold text-uts-teal">
                    $50
                    <span className="text-sm text-gray-300 font-normal">
                      /mo
                    </span>
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span>Your Claude Sub</span>
                  <span className="text-2xl font-bold text-uts-teal">
                    $20
                    <span className="text-sm text-gray-300 font-normal">
                      /mo
                    </span>
                  </span>
                </div>
              </div>
              <div className="mt-8 pt-6 border-t border-white/20">
                <p className="text-sm text-gray-300 mb-4">
                  *You pay the UTS parent directly. UTSPA handles no money.
                </p>
                <a href="mailto:pamela.wong@utschools.ca?subject=Connect%20With%20a%20UTS%20Family" className="w-full bg-white text-uts-navy font-bold py-3 px-6 rounded-lg hover:bg-gray-100 transition-colors block text-center">
                  Connect With a UTS Family
                </a>
              </div>
            </div>

            <div className="bg-amber-50 border border-amber-200 p-6 rounded-xl">
              <div className="flex items-start mb-4">
                <AlertCircle className="w-6 h-6 text-amber-600 mr-3 flex-shrink-0" />
                <h3 className="text-lg font-bold text-amber-900">
                  Honest Expectations
                </h3>
              </div>
              <ul className="space-y-3 text-amber-800 text-sm">
                <li className="flex items-start">
                  <span className="mr-2">•</span>
                  <span>
                    This is a high school student, not a McKinsey consultant.
                  </span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">•</span>
                  <span>
                    Claude Cowork is a new product in research preview. It may
                    have bugs.
                  </span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">•</span>
                  <span>
                    Response times for maintenance may be measured in days
                    (students have school!).
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>);

}